package com.bupt.core.system.dao;

import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.apache.ibatis.annotations.Param;

import com.bupt.core.system.dto.UserDTO;
import com.bupt.core.system.model.User;
import com.bupt.core.system.model.UserExample;

public interface UserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_security_user
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	int countByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_security_user
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	int deleteByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_security_user
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	int deleteByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_security_user
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_security_user
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_security_user
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	List<User> selectByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_security_user
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	User selectByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_security_user
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	int updateByExampleSelective(@Param("record") User record,
			@Param("example") UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_security_user
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	int updateByExample(@Param("record") User record,
			@Param("example") UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_security_user
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_security_user
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	int updateByPrimaryKey(User record);
	
	/**
	 * 百万级分页优化
	 */
	public List<User> listResults(@Param("start") int start, @Param("limit") int limit, @Param("sortName") String sortName, @Param("sortOrder") String sortOrder, @Param("UserExample") UserExample example);
	
}