package com.bupt.core.system.dao;

import com.bupt.core.system.model.UserInfo;
import com.bupt.core.system.model.UserInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_user_info
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    int countByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_user_info
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    int deleteByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_user_info
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    int deleteByPrimaryKey(Integer userInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_user_info
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_user_info
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_user_info
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    List<UserInfo> selectByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_user_info
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    UserInfo selectByPrimaryKey(Integer userInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_user_info
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    int updateByExampleSelective(@Param("record") UserInfo record, @Param("example") UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_user_info
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    int updateByExample(@Param("record") UserInfo record, @Param("example") UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_user_info
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_security_user_info
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    int updateByPrimaryKey(UserInfo record);
}