package com.bupt.core.security.dao;

import com.bupt.core.security.model.Role;
import com.bupt.core.security.model.RoleExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_security_role
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	int countByExample(RoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_security_role
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	int deleteByExample(RoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_security_role
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	int deleteByPrimaryKey(Integer roleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_security_role
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	int insert(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_security_role
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	int insertSelective(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_security_role
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	List<Role> selectByExample(RoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_security_role
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	Role selectByPrimaryKey(Integer roleId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_security_role
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	int updateByExampleSelective(@Param("record") Role record,
			@Param("example") RoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_security_role
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	int updateByExample(@Param("record") Role record,
			@Param("example") RoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_security_role
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	int updateByPrimaryKeySelective(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_security_role
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	int updateByPrimaryKey(Role record);
}