package com.bupt.core.security.model;

public class Privilege {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_security_privilege.privilege_id
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	private Integer privilegeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_security_privilege.parent_id
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	private Integer parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_security_privilege.description
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_security_privilege.name
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_security_privilege.display_name
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	private String displayName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_security_privilege.level
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	private Byte level;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_security_privilege.is_leaf
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	private Boolean isLeaf;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_security_privilege.url
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_security_privilege.target
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	private String target;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_security_privilege.order_num
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	private Integer orderNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_security_privilege.display
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	private Boolean display;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_security_privilege.type
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	private String type;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_security_privilege.privilege_id
	 * @return  the value of t_security_privilege.privilege_id
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	public Integer getPrivilegeId() {
		return privilegeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_security_privilege.privilege_id
	 * @param privilegeId  the value for t_security_privilege.privilege_id
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	public void setPrivilegeId(Integer privilegeId) {
		this.privilegeId = privilegeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_security_privilege.parent_id
	 * @return  the value of t_security_privilege.parent_id
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_security_privilege.parent_id
	 * @param parentId  the value for t_security_privilege.parent_id
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_security_privilege.description
	 * @return  the value of t_security_privilege.description
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_security_privilege.description
	 * @param description  the value for t_security_privilege.description
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_security_privilege.name
	 * @return  the value of t_security_privilege.name
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_security_privilege.name
	 * @param name  the value for t_security_privilege.name
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_security_privilege.display_name
	 * @return  the value of t_security_privilege.display_name
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	public String getDisplayName() {
		return displayName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_security_privilege.display_name
	 * @param displayName  the value for t_security_privilege.display_name
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	public void setDisplayName(String displayName) {
		this.displayName = displayName == null ? null : displayName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_security_privilege.level
	 * @return  the value of t_security_privilege.level
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	public Byte getLevel() {
		return level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_security_privilege.level
	 * @param level  the value for t_security_privilege.level
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	public void setLevel(Byte level) {
		this.level = level;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_security_privilege.is_leaf
	 * @return  the value of t_security_privilege.is_leaf
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	public Boolean getIsLeaf() {
		return isLeaf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_security_privilege.is_leaf
	 * @param isLeaf  the value for t_security_privilege.is_leaf
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	public void setIsLeaf(Boolean isLeaf) {
		this.isLeaf = isLeaf;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_security_privilege.url
	 * @return  the value of t_security_privilege.url
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_security_privilege.url
	 * @param url  the value for t_security_privilege.url
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_security_privilege.target
	 * @return  the value of t_security_privilege.target
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	public String getTarget() {
		return target;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_security_privilege.target
	 * @param target  the value for t_security_privilege.target
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	public void setTarget(String target) {
		this.target = target == null ? null : target.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_security_privilege.order_num
	 * @return  the value of t_security_privilege.order_num
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	public Integer getOrderNum() {
		return orderNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_security_privilege.order_num
	 * @param orderNum  the value for t_security_privilege.order_num
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	public void setOrderNum(Integer orderNum) {
		this.orderNum = orderNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_security_privilege.display
	 * @return  the value of t_security_privilege.display
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	public Boolean getDisplay() {
		return display;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_security_privilege.display
	 * @param display  the value for t_security_privilege.display
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	public void setDisplay(Boolean display) {
		this.display = display;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_security_privilege.type
	 * @return  the value of t_security_privilege.type
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_security_privilege.type
	 * @param type  the value for t_security_privilege.type
	 * @mbggenerated  Sun Jul 21 16:19:05 CST 2013
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}
}