package com.bupt.core.system.model;

public class Department {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_security_department.department_id
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    private Integer departmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_security_department.name
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_security_department.level
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_security_department.is_leaf
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    private Boolean isLeaf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_security_department.parent_id
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    private Integer parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_security_department.department_id
     *
     * @return the value of t_security_department.department_id
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_security_department.department_id
     *
     * @param departmentId the value for t_security_department.department_id
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_security_department.name
     *
     * @return the value of t_security_department.name
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_security_department.name
     *
     * @param name the value for t_security_department.name
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_security_department.level
     *
     * @return the value of t_security_department.level
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_security_department.level
     *
     * @param level the value for t_security_department.level
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_security_department.is_leaf
     *
     * @return the value of t_security_department.is_leaf
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    public Boolean getIsLeaf() {
        return isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_security_department.is_leaf
     *
     * @param isLeaf the value for t_security_department.is_leaf
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    public void setIsLeaf(Boolean isLeaf) {
        this.isLeaf = isLeaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_security_department.parent_id
     *
     * @return the value of t_security_department.parent_id
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_security_department.parent_id
     *
     * @param parentId the value for t_security_department.parent_id
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
}