package com.bupt.core.system.model;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_security_user_info.user_info_id
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    private Integer userInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_security_user_info.user_id
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_security_user_info.email
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_security_user_info.telephone
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_security_user_info.station
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    private String station;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_security_user_info.birthday
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_security_user_info.hireday
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    private Date hireday;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_security_user_info.user_info_id
     *
     * @return the value of t_security_user_info.user_info_id
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    public Integer getUserInfoId() {
        return userInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_security_user_info.user_info_id
     *
     * @param userInfoId the value for t_security_user_info.user_info_id
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    public void setUserInfoId(Integer userInfoId) {
        this.userInfoId = userInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_security_user_info.user_id
     *
     * @return the value of t_security_user_info.user_id
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_security_user_info.user_id
     *
     * @param userId the value for t_security_user_info.user_id
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_security_user_info.email
     *
     * @return the value of t_security_user_info.email
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_security_user_info.email
     *
     * @param email the value for t_security_user_info.email
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_security_user_info.telephone
     *
     * @return the value of t_security_user_info.telephone
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_security_user_info.telephone
     *
     * @param telephone the value for t_security_user_info.telephone
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_security_user_info.station
     *
     * @return the value of t_security_user_info.station
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    public String getStation() {
        return station;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_security_user_info.station
     *
     * @param station the value for t_security_user_info.station
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    public void setStation(String station) {
        this.station = station == null ? null : station.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_security_user_info.birthday
     *
     * @return the value of t_security_user_info.birthday
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_security_user_info.birthday
     *
     * @param birthday the value for t_security_user_info.birthday
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_security_user_info.hireday
     *
     * @return the value of t_security_user_info.hireday
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    public Date getHireday() {
        return hireday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_security_user_info.hireday
     *
     * @param hireday the value for t_security_user_info.hireday
     *
     * @mbggenerated Mon Jul 22 00:14:59 CST 2013
     */
    public void setHireday(Date hireday) {
        this.hireday = hireday;
    }
}